export const SIGN_UP = 'SIGN_UP'
export const AUTHENTICATED = 'AUTHENTICATED'
export const LOGGED_OUT = 'LOGGED_OUT'
export const LOG_IN = 'LOG_IN'
export const ERROR = 'ERROR'
export const USER_DASHBOARD = 'USER_DASHBOARD'
export const GET_USERS = 'GET_USERS'